package com.thewizrd.simpleweather.notifications;

import androidx.annotation.DrawableRes;
import androidx.annotation.IntRange;

import com.thewizrd.simpleweather.R;

public final class WeatherNotificationTemp {
    @DrawableRes
    public static int getTempDrawable(@IntRange(from = -140, to = 140) int temp) {
        switch (temp) {
            case -140:
                return R.drawable.notification_temp_neg140;
            case -139:
                return R.drawable.notification_temp_neg139;
            case -138:
                return R.drawable.notification_temp_neg138;
            case -137:
                return R.drawable.notification_temp_neg137;
            case -136:
                return R.drawable.notification_temp_neg136;
            case -135:
                return R.drawable.notification_temp_neg135;
            case -134:
                return R.drawable.notification_temp_neg134;
            case -133:
                return R.drawable.notification_temp_neg133;
            case -132:
                return R.drawable.notification_temp_neg132;
            case -131:
                return R.drawable.notification_temp_neg131;
            case -130:
                return R.drawable.notification_temp_neg130;
            case -129:
                return R.drawable.notification_temp_neg129;
            case -128:
                return R.drawable.notification_temp_neg128;
            case -127:
                return R.drawable.notification_temp_neg127;
            case -126:
                return R.drawable.notification_temp_neg126;
            case -125:
                return R.drawable.notification_temp_neg125;
            case -124:
                return R.drawable.notification_temp_neg124;
            case -123:
                return R.drawable.notification_temp_neg123;
            case -122:
                return R.drawable.notification_temp_neg122;
            case -121:
                return R.drawable.notification_temp_neg121;
            case -120:
                return R.drawable.notification_temp_neg120;
            case -119:
                return R.drawable.notification_temp_neg119;
            case -118:
                return R.drawable.notification_temp_neg118;
            case -117:
                return R.drawable.notification_temp_neg117;
            case -116:
                return R.drawable.notification_temp_neg116;
            case -115:
                return R.drawable.notification_temp_neg115;
            case -114:
                return R.drawable.notification_temp_neg114;
            case -113:
                return R.drawable.notification_temp_neg113;
            case -112:
                return R.drawable.notification_temp_neg112;
            case -111:
                return R.drawable.notification_temp_neg111;
            case -110:
                return R.drawable.notification_temp_neg110;
            case -109:
                return R.drawable.notification_temp_neg109;
            case -108:
                return R.drawable.notification_temp_neg108;
            case -107:
                return R.drawable.notification_temp_neg107;
            case -106:
                return R.drawable.notification_temp_neg106;
            case -105:
                return R.drawable.notification_temp_neg105;
            case -104:
                return R.drawable.notification_temp_neg104;
            case -103:
                return R.drawable.notification_temp_neg103;
            case -102:
                return R.drawable.notification_temp_neg102;
            case -101:
                return R.drawable.notification_temp_neg101;
            case -100:
                return R.drawable.notification_temp_neg100;
            case -99:
                return R.drawable.notification_temp_neg99;
            case -98:
                return R.drawable.notification_temp_neg98;
            case -97:
                return R.drawable.notification_temp_neg97;
            case -96:
                return R.drawable.notification_temp_neg96;
            case -95:
                return R.drawable.notification_temp_neg95;
            case -94:
                return R.drawable.notification_temp_neg94;
            case -93:
                return R.drawable.notification_temp_neg93;
            case -92:
                return R.drawable.notification_temp_neg92;
            case -91:
                return R.drawable.notification_temp_neg91;
            case -90:
                return R.drawable.notification_temp_neg90;
            case -89:
                return R.drawable.notification_temp_neg89;
            case -88:
                return R.drawable.notification_temp_neg88;
            case -87:
                return R.drawable.notification_temp_neg87;
            case -86:
                return R.drawable.notification_temp_neg86;
            case -85:
                return R.drawable.notification_temp_neg85;
            case -84:
                return R.drawable.notification_temp_neg84;
            case -83:
                return R.drawable.notification_temp_neg83;
            case -82:
                return R.drawable.notification_temp_neg82;
            case -81:
                return R.drawable.notification_temp_neg81;
            case -80:
                return R.drawable.notification_temp_neg80;
            case -79:
                return R.drawable.notification_temp_neg79;
            case -78:
                return R.drawable.notification_temp_neg78;
            case -77:
                return R.drawable.notification_temp_neg77;
            case -76:
                return R.drawable.notification_temp_neg76;
            case -75:
                return R.drawable.notification_temp_neg75;
            case -74:
                return R.drawable.notification_temp_neg74;
            case -73:
                return R.drawable.notification_temp_neg73;
            case -72:
                return R.drawable.notification_temp_neg72;
            case -71:
                return R.drawable.notification_temp_neg71;
            case -70:
                return R.drawable.notification_temp_neg70;
            case -69:
                return R.drawable.notification_temp_neg69;
            case -68:
                return R.drawable.notification_temp_neg68;
            case -67:
                return R.drawable.notification_temp_neg67;
            case -66:
                return R.drawable.notification_temp_neg66;
            case -65:
                return R.drawable.notification_temp_neg65;
            case -64:
                return R.drawable.notification_temp_neg64;
            case -63:
                return R.drawable.notification_temp_neg63;
            case -62:
                return R.drawable.notification_temp_neg62;
            case -61:
                return R.drawable.notification_temp_neg61;
            case -60:
                return R.drawable.notification_temp_neg60;
            case -59:
                return R.drawable.notification_temp_neg59;
            case -58:
                return R.drawable.notification_temp_neg58;
            case -57:
                return R.drawable.notification_temp_neg57;
            case -56:
                return R.drawable.notification_temp_neg56;
            case -55:
                return R.drawable.notification_temp_neg55;
            case -54:
                return R.drawable.notification_temp_neg54;
            case -53:
                return R.drawable.notification_temp_neg53;
            case -52:
                return R.drawable.notification_temp_neg52;
            case -51:
                return R.drawable.notification_temp_neg51;
            case -50:
                return R.drawable.notification_temp_neg50;
            case -49:
                return R.drawable.notification_temp_neg49;
            case -48:
                return R.drawable.notification_temp_neg48;
            case -47:
                return R.drawable.notification_temp_neg47;
            case -46:
                return R.drawable.notification_temp_neg46;
            case -45:
                return R.drawable.notification_temp_neg45;
            case -44:
                return R.drawable.notification_temp_neg44;
            case -43:
                return R.drawable.notification_temp_neg43;
            case -42:
                return R.drawable.notification_temp_neg42;
            case -41:
                return R.drawable.notification_temp_neg41;
            case -40:
                return R.drawable.notification_temp_neg40;
            case -39:
                return R.drawable.notification_temp_neg39;
            case -38:
                return R.drawable.notification_temp_neg38;
            case -37:
                return R.drawable.notification_temp_neg37;
            case -36:
                return R.drawable.notification_temp_neg36;
            case -35:
                return R.drawable.notification_temp_neg35;
            case -34:
                return R.drawable.notification_temp_neg34;
            case -33:
                return R.drawable.notification_temp_neg33;
            case -32:
                return R.drawable.notification_temp_neg32;
            case -31:
                return R.drawable.notification_temp_neg31;
            case -30:
                return R.drawable.notification_temp_neg30;
            case -29:
                return R.drawable.notification_temp_neg29;
            case -28:
                return R.drawable.notification_temp_neg28;
            case -27:
                return R.drawable.notification_temp_neg27;
            case -26:
                return R.drawable.notification_temp_neg26;
            case -25:
                return R.drawable.notification_temp_neg25;
            case -24:
                return R.drawable.notification_temp_neg24;
            case -23:
                return R.drawable.notification_temp_neg23;
            case -22:
                return R.drawable.notification_temp_neg22;
            case -21:
                return R.drawable.notification_temp_neg21;
            case -20:
                return R.drawable.notification_temp_neg20;
            case -19:
                return R.drawable.notification_temp_neg19;
            case -18:
                return R.drawable.notification_temp_neg18;
            case -17:
                return R.drawable.notification_temp_neg17;
            case -16:
                return R.drawable.notification_temp_neg16;
            case -15:
                return R.drawable.notification_temp_neg15;
            case -14:
                return R.drawable.notification_temp_neg14;
            case -13:
                return R.drawable.notification_temp_neg13;
            case -12:
                return R.drawable.notification_temp_neg12;
            case -11:
                return R.drawable.notification_temp_neg11;
            case -10:
                return R.drawable.notification_temp_neg10;
            case -9:
                return R.drawable.notification_temp_neg9;
            case -8:
                return R.drawable.notification_temp_neg8;
            case -7:
                return R.drawable.notification_temp_neg7;
            case -6:
                return R.drawable.notification_temp_neg6;
            case -5:
                return R.drawable.notification_temp_neg5;
            case -4:
                return R.drawable.notification_temp_neg4;
            case -3:
                return R.drawable.notification_temp_neg3;
            case -2:
                return R.drawable.notification_temp_neg2;
            case -1:
                return R.drawable.notification_temp_neg1;
            case 0:
                return R.drawable.notification_temp_pos0;
            case 1:
                return R.drawable.notification_temp_pos1;
            case 2:
                return R.drawable.notification_temp_pos2;
            case 3:
                return R.drawable.notification_temp_pos3;
            case 4:
                return R.drawable.notification_temp_pos4;
            case 5:
                return R.drawable.notification_temp_pos5;
            case 6:
                return R.drawable.notification_temp_pos6;
            case 7:
                return R.drawable.notification_temp_pos7;
            case 8:
                return R.drawable.notification_temp_pos8;
            case 9:
                return R.drawable.notification_temp_pos9;
            case 10:
                return R.drawable.notification_temp_pos10;
            case 11:
                return R.drawable.notification_temp_pos11;
            case 12:
                return R.drawable.notification_temp_pos12;
            case 13:
                return R.drawable.notification_temp_pos13;
            case 14:
                return R.drawable.notification_temp_pos14;
            case 15:
                return R.drawable.notification_temp_pos15;
            case 16:
                return R.drawable.notification_temp_pos16;
            case 17:
                return R.drawable.notification_temp_pos17;
            case 18:
                return R.drawable.notification_temp_pos18;
            case 19:
                return R.drawable.notification_temp_pos19;
            case 20:
                return R.drawable.notification_temp_pos20;
            case 21:
                return R.drawable.notification_temp_pos21;
            case 22:
                return R.drawable.notification_temp_pos22;
            case 23:
                return R.drawable.notification_temp_pos23;
            case 24:
                return R.drawable.notification_temp_pos24;
            case 25:
                return R.drawable.notification_temp_pos25;
            case 26:
                return R.drawable.notification_temp_pos26;
            case 27:
                return R.drawable.notification_temp_pos27;
            case 28:
                return R.drawable.notification_temp_pos28;
            case 29:
                return R.drawable.notification_temp_pos29;
            case 30:
                return R.drawable.notification_temp_pos30;
            case 31:
                return R.drawable.notification_temp_pos31;
            case 32:
                return R.drawable.notification_temp_pos32;
            case 33:
                return R.drawable.notification_temp_pos33;
            case 34:
                return R.drawable.notification_temp_pos34;
            case 35:
                return R.drawable.notification_temp_pos35;
            case 36:
                return R.drawable.notification_temp_pos36;
            case 37:
                return R.drawable.notification_temp_pos37;
            case 38:
                return R.drawable.notification_temp_pos38;
            case 39:
                return R.drawable.notification_temp_pos39;
            case 40:
                return R.drawable.notification_temp_pos40;
            case 41:
                return R.drawable.notification_temp_pos41;
            case 42:
                return R.drawable.notification_temp_pos42;
            case 43:
                return R.drawable.notification_temp_pos43;
            case 44:
                return R.drawable.notification_temp_pos44;
            case 45:
                return R.drawable.notification_temp_pos45;
            case 46:
                return R.drawable.notification_temp_pos46;
            case 47:
                return R.drawable.notification_temp_pos47;
            case 48:
                return R.drawable.notification_temp_pos48;
            case 49:
                return R.drawable.notification_temp_pos49;
            case 50:
                return R.drawable.notification_temp_pos50;
            case 51:
                return R.drawable.notification_temp_pos51;
            case 52:
                return R.drawable.notification_temp_pos52;
            case 53:
                return R.drawable.notification_temp_pos53;
            case 54:
                return R.drawable.notification_temp_pos54;
            case 55:
                return R.drawable.notification_temp_pos55;
            case 56:
                return R.drawable.notification_temp_pos56;
            case 57:
                return R.drawable.notification_temp_pos57;
            case 58:
                return R.drawable.notification_temp_pos58;
            case 59:
                return R.drawable.notification_temp_pos59;
            case 60:
                return R.drawable.notification_temp_pos60;
            case 61:
                return R.drawable.notification_temp_pos61;
            case 62:
                return R.drawable.notification_temp_pos62;
            case 63:
                return R.drawable.notification_temp_pos63;
            case 64:
                return R.drawable.notification_temp_pos64;
            case 65:
                return R.drawable.notification_temp_pos65;
            case 66:
                return R.drawable.notification_temp_pos66;
            case 67:
                return R.drawable.notification_temp_pos67;
            case 68:
                return R.drawable.notification_temp_pos68;
            case 69:
                return R.drawable.notification_temp_pos69;
            case 70:
                return R.drawable.notification_temp_pos70;
            case 71:
                return R.drawable.notification_temp_pos71;
            case 72:
                return R.drawable.notification_temp_pos72;
            case 73:
                return R.drawable.notification_temp_pos73;
            case 74:
                return R.drawable.notification_temp_pos74;
            case 75:
                return R.drawable.notification_temp_pos75;
            case 76:
                return R.drawable.notification_temp_pos76;
            case 77:
                return R.drawable.notification_temp_pos77;
            case 78:
                return R.drawable.notification_temp_pos78;
            case 79:
                return R.drawable.notification_temp_pos79;
            case 80:
                return R.drawable.notification_temp_pos80;
            case 81:
                return R.drawable.notification_temp_pos81;
            case 82:
                return R.drawable.notification_temp_pos82;
            case 83:
                return R.drawable.notification_temp_pos83;
            case 84:
                return R.drawable.notification_temp_pos84;
            case 85:
                return R.drawable.notification_temp_pos85;
            case 86:
                return R.drawable.notification_temp_pos86;
            case 87:
                return R.drawable.notification_temp_pos87;
            case 88:
                return R.drawable.notification_temp_pos88;
            case 89:
                return R.drawable.notification_temp_pos89;
            case 90:
                return R.drawable.notification_temp_pos90;
            case 91:
                return R.drawable.notification_temp_pos91;
            case 92:
                return R.drawable.notification_temp_pos92;
            case 93:
                return R.drawable.notification_temp_pos93;
            case 94:
                return R.drawable.notification_temp_pos94;
            case 95:
                return R.drawable.notification_temp_pos95;
            case 96:
                return R.drawable.notification_temp_pos96;
            case 97:
                return R.drawable.notification_temp_pos97;
            case 98:
                return R.drawable.notification_temp_pos98;
            case 99:
                return R.drawable.notification_temp_pos99;
            case 100:
                return R.drawable.notification_temp_pos100;
            case 101:
                return R.drawable.notification_temp_pos101;
            case 102:
                return R.drawable.notification_temp_pos102;
            case 103:
                return R.drawable.notification_temp_pos103;
            case 104:
                return R.drawable.notification_temp_pos104;
            case 105:
                return R.drawable.notification_temp_pos105;
            case 106:
                return R.drawable.notification_temp_pos106;
            case 107:
                return R.drawable.notification_temp_pos107;
            case 108:
                return R.drawable.notification_temp_pos108;
            case 109:
                return R.drawable.notification_temp_pos109;
            case 110:
                return R.drawable.notification_temp_pos110;
            case 111:
                return R.drawable.notification_temp_pos111;
            case 112:
                return R.drawable.notification_temp_pos112;
            case 113:
                return R.drawable.notification_temp_pos113;
            case 114:
                return R.drawable.notification_temp_pos114;
            case 115:
                return R.drawable.notification_temp_pos115;
            case 116:
                return R.drawable.notification_temp_pos116;
            case 117:
                return R.drawable.notification_temp_pos117;
            case 118:
                return R.drawable.notification_temp_pos118;
            case 119:
                return R.drawable.notification_temp_pos119;
            case 120:
                return R.drawable.notification_temp_pos120;
            case 121:
                return R.drawable.notification_temp_pos121;
            case 122:
                return R.drawable.notification_temp_pos122;
            case 123:
                return R.drawable.notification_temp_pos123;
            case 124:
                return R.drawable.notification_temp_pos124;
            case 125:
                return R.drawable.notification_temp_pos125;
            case 126:
                return R.drawable.notification_temp_pos126;
            case 127:
                return R.drawable.notification_temp_pos127;
            case 128:
                return R.drawable.notification_temp_pos128;
            case 129:
                return R.drawable.notification_temp_pos129;
            case 130:
                return R.drawable.notification_temp_pos130;
            case 131:
                return R.drawable.notification_temp_pos131;
            case 132:
                return R.drawable.notification_temp_pos132;
            case 133:
                return R.drawable.notification_temp_pos133;
            case 134:
                return R.drawable.notification_temp_pos134;
            case 135:
                return R.drawable.notification_temp_pos135;
            case 136:
                return R.drawable.notification_temp_pos136;
            case 137:
                return R.drawable.notification_temp_pos137;
            case 138:
                return R.drawable.notification_temp_pos138;
            case 139:
                return R.drawable.notification_temp_pos139;
            case 140:
                return R.drawable.notification_temp_pos140;
            default:
                return R.drawable.notification_temp_unknown;
        }
    }
}
