plugins {
    id 'com.android.application'
    id 'androidx.navigation.safeargs'
    id 'com.android.legacy-kapt'
    id 'com.google.devtools.ksp'
}

android {
    compileSdk = libs.versions.compileSdkVersion.get().toInteger()

    defaultConfig {
        applicationId "com.thewizrd.simpleweather"
        testApplicationId "com.thewizrd.simpleweather.test"
        // Specifies the fully-qualified class name of the test instrumentation runner.
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        minSdkVersion libs.versions.minSdkVersion.get().toInteger()
        targetSdkVersion libs.versions.targetSdkVersion.get().toInteger()
        // NOTE: Version Code Format (TargetSDK, Version Name, Build Number, Variant Code (Android: 0, WearOS: 1)
        // ex) 345100131 = (34, 5.10, 013, 0)
        versionCode 375140130
        versionName "5.14.2"

        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            debuggable true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            manifestPlaceholders = [allowBackup: false]
        }
        release {
            minifyEnabled true
            shrinkResources true
            crunchPngs true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            manifestPlaceholders = [allowBackup: true]
        }
    }

    buildFeatures {
        dataBinding true
        viewBinding true
        buildConfig true
        resValues true
    }

    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true
        // Sets Java compatibility to Java 8
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlin {
        jvmToolchain(21)
    }

    sourceSets {
        main {
            manifest.srcFile 'src/main/AndroidManifest.xml'
        }
        fullgms {
            manifest.srcFile 'src/fullgms/AndroidManifest.xml'
        }
        nongms {
            manifest.srcFile 'src/main/AndroidManifest.xml'
        }
    }

    flavorDimensions 'gms'
    productFlavors {
        nongms {
            dimension 'gms'
            applicationIdSuffix ".foss"
            versionNameSuffix "-nongms"
            buildConfigField "boolean", "IS_NONGMS", "true"
        }
        fullgms {
            dimension 'gms'
            // Read the API key from ./secure.properties into R.string.maps_api_key
            def secureProps = new Properties()
            if (file("../secure.properties").exists()) {
                file("../secure.properties")?.withInputStream { secureProps.load(it) }
            }
            resValue "string", "maps_api_key", (secureProps.getProperty("MAPS_API_KEY") ?: "")
            buildConfigField "boolean", "IS_NONGMS", "false"
        }
    }
    namespace 'com.thewizrd.simpleweather'
}

dependencies {
    implementation project(":shared_resources")
    implementation project(":weather-api")
    implementation project(":common")
    fullgmsImplementation project(":extras")

    // Unit Testing
    androidTestImplementation libs.test.core

    // AndroidJUnitRunner and JUnit Rules
    androidTestImplementation libs.test.runner
    androidTestImplementation libs.test.rules

    // Assertions
    androidTestImplementation libs.test.ext.junit
    androidTestImplementation libs.test.ext.truth
    androidTestImplementation libs.google.truth

    coreLibraryDesugaring libs.desugar.jdk.libs

    // Kotlin
    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android

    implementation libs.core.ktx
    implementation libs.core.splashscreen
    implementation libs.appcompat
    implementation libs.fragment.ktx
    implementation libs.material
    implementation libs.arch.core.runtime
    implementation libs.cardview
    implementation libs.recyclerview
    implementation libs.preference.ktx
    implementation libs.legacy.support.v4
    implementation libs.annotation
    implementation libs.constraintlayout
    implementation libs.vectordrawable
    implementation libs.palette.ktx
    implementation libs.swiperefreshlayout
    implementation libs.paging.runtime.ktx
    implementation libs.work.runtime.ktx
    implementation libs.work.multiprocess

    implementation libs.lifecycle.extensions
    implementation libs.lifecycle.runtime.ktx

    implementation libs.navigation.fragment.ktx
    implementation libs.navigation.ui.ktx

    implementation libs.room.runtime
    ksp libs.room.compiler

    implementation libs.okhttp
    implementation libs.glide
    ksp libs.glide.ksp
    implementation libs.timber
    implementation libs.icu4j
    implementation libs.colorpickerview

    implementation libs.moshi.kotlin
    ksp libs.moshi.kotlin.codegen
    implementation libs.moshi.adapters

    // Firebase
    fullgmsImplementation platform(libs.firebase.bom)
    fullgmsImplementation libs.firebase.analytics
    fullgmsImplementation libs.firebase.crashlytics
    fullgmsImplementation libs.firebase.auth
    fullgmsImplementation libs.firebase.firestore
    fullgmsImplementation libs.firebase.messaging
    fullgmsImplementation libs.firebase.storage
    fullgmsImplementation libs.firebase.database
    fullgmsImplementation libs.firebase.config
    fullgmsImplementation libs.firebase.perf

    fullgmsImplementation libs.gms.play.services.base
    fullgmsImplementation libs.gms.play.services.location
    fullgmsImplementation libs.gms.play.services.maps
    fullgmsImplementation libs.gms.play.services.wearable
    fullgmsImplementation libs.play.app.update.ktx
    fullgmsImplementation libs.play.feature.delivery.ktx
    fullgmsImplementation libs.play.review.ktx
    fullgmsImplementation libs.kotlinx.coroutines.play.services

    nongmsImplementation libs.osmdroid.android
}

if (getGradle().getStartParameter().getTaskRequests().toString().contains("Fullgms")) {
    apply plugin: 'com.google.gms.google-services'
    apply plugin: 'com.google.firebase.crashlytics'
    apply plugin: 'com.google.firebase.firebase-perf'
}
