name: Android CI

env:
  module: app
  app_name: SimpleWeather
  variant: nongms

on:
  push:
    branches: [ "public" ]
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    # Set Current Date As Env Variable
    - name: Set current date as env variable
      run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # APK Debug
    - name: Build debug APK
      run: ./gradlew :${{ env.module }}:assemble${{ env.variant }}Debug
    # Upload apk
    - name: Upload debug APK
      uses: actions/upload-artifact@v3
      with:
          name: ${{ env.module }}-${{ env.variant }}-${{ env.date_today }}-debug.apk
          path: ${{ env.module }}/build/outputs/apk/${{ env.variant }}/debug/${{ env.module }}-${{ env.variant }}-debug.apk
  release:
    name: Release APK
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # APK Release
    - name: Build release APK
      run: ./gradlew :${{ env.module }}:assemble${{ env.variant }}
    # Upload apk
    - name: Upload release APK
      uses: actions/upload-artifact@v3
      with:
          name: ${{ env.module }}-${{ env.variant }}-${{ env.date_today }}-release.apk
          path: ${{ env.module }}/build/outputs/apk/${{ env.variant }}/release/${{ env.module }}-${{ env.variant }}-release.apk
